INSERT INTO Brand (name) VALUES ('Brand1');
INSERT INTO Brand (name) VALUES ('Brand2');
INSERT INTO Brand (name) VALUES ('Brand3');
INSERT INTO Brand (name) VALUES ('Brand4');
INSERT INTO Brand (name) VALUES ('Brand5');
INSERT INTO Brand (name) VALUES ('Brand6');
INSERT INTO Brand (name) VALUES ('Brand7');
INSERT INTO Brand (name) VALUES ('Brand8');
INSERT INTO Brand (name) VALUES ('Brand9');
INSERT INTO Brand (name) VALUES ('Brand10');
INSERT INTO Model (name, brand_id) VALUES ('Model1', 1);
INSERT INTO Model (name, brand_id) VALUES ('Model2', 1);
INSERT INTO Model (name, brand_id) VALUES ('Model3', 2);
INSERT INTO Model (name, brand_id) VALUES ('Model4', 2);
INSERT INTO Model (name, brand_id) VALUES ('Model5', 3);
INSERT INTO Model (name, brand_id) VALUES ('Model6', 3);
INSERT INTO Model (name, brand_id) VALUES ('Model7', 4);
INSERT INTO Model (name, brand_id) VALUES ('Model8', 4);
INSERT INTO Model (name, brand_id) VALUES ('Model9', 5);
INSERT INTO Model (name, brand_id) VALUES ('Model10', 5);
INSERT INTO Model (name, brand_id) VALUES ('Model11', 6);
INSERT INTO Model (name, brand_id) VALUES ('Model12', 6);
INSERT INTO Model (name, brand_id) VALUES ('Model13', 7);
INSERT INTO Model (name, brand_id) VALUES ('Model14', 7);
INSERT INTO Model (name, brand_id) VALUES ('Model15', 8);
INSERT INTO Model (name, brand_id) VALUES ('Model16', 8);
INSERT INTO Model (name, brand_id) VALUES ('Model17', 9);
INSERT INTO Model (name, brand_id) VALUES ('Model18', 9);
INSERT INTO Model (name, brand_id) VALUES ('Model19', 10);
INSERT INTO Model (name, brand_id) VALUES ('Model20', 10);
INSERT INTO Car (licenseplate, model_id, brand_id, yearofproduction, mileage, color, price, sold, owner_id) VALUES ('AB123CD', 1, 1, 2020, 50000, 'Bianco', 25000, false, null);
INSERT INTO Car (licenseplate, model_id, brand_id, yearofproduction, mileage, color, price, sold, owner_id) VALUES ('XY789ZA', 2, 1, 2019, 60000, 'Nero', 22000, false, null);
INSERT INTO Car (licenseplate, model_id, brand_id, yearofproduction, mileage, color, price, sold, owner_id) VALUES ('CD456EF', 3, 2, 2022, 35000, 'Rosso', 28000, false, null);
INSERT INTO Car (licenseplate, model_id, brand_id, yearofproduction, mileage, color, price, sold, owner_id) VALUES ('ZA987XY', 4, 2, 2021, 40000, 'Blu', 24000, false, null);
INSERT INTO Car (licenseplate, model_id, brand_id, yearofproduction, mileage, color, price, sold, owner_id) VALUES ('EF123AB', 5, 3, 2020, 45000, 'Verde', 26000, false, null);
INSERT INTO Car (licenseplate, model_id, brand_id, yearofproduction, mileage, color, price, sold, owner_id) VALUES ('GH789IJ', 6, 3, 2021, 30000, 'Viola', 30000, false, null);
INSERT INTO Car (licenseplate, model_id, brand_id, yearofproduction, mileage, color, price, sold, owner_id) VALUES ('KL456MN', 7, 4, 2022, 32000, 'Arancione', 27000, false, null);
INSERT INTO Car (licenseplate, model_id, brand_id, yearofproduction, mileage, color, price, sold, owner_id) VALUES ('OP123QR', 8, 4, 2019, 70000, 'Argento', 20000, false, null);
INSERT INTO Car (licenseplate, model_id, brand_id, yearofproduction, mileage, color, price, sold, owner_id) VALUES ('ST789UV', 9, 5, 2020, 55000, 'Bianco', 23000, false, null);
INSERT INTO Car (licenseplate, model_id, brand_id, yearofproduction, mileage, color, price, sold, owner_id) VALUES ('WX123YZ', 10, 5, 2022, 25000, 'Nero', 29000, false, null);
INSERT INTO Car (licenseplate, model_id, brand_id, yearofproduction, mileage, color, price, sold, owner_id) VALUES ('YZ789AB', 11, 6, 2019, 60000, 'Rosso', 22000, false, null);
INSERT INTO Car (licenseplate, model_id, brand_id, yearofproduction, mileage, color, price, sold, owner_id) VALUES ('CD123EF', 12, 6, 2021, 40000, 'Blu', 26000, false, null);
INSERT INTO Car (licenseplate, model_id, brand_id, yearofproduction, mileage, color, price, sold, owner_id) VALUES ('GH456IJ', 13, 7, 2020, 35000, 'Verde', 28000, false, null);
INSERT INTO Car (licenseplate, model_id, brand_id, yearofproduction, mileage, color, price, sold, owner_id) VALUES ('KL789MN', 14, 7, 2022, 30000, 'Viola', 31000, false, null);
INSERT INTO Car (licenseplate, model_id, brand_id, yearofproduction, mileage, color, price, sold, owner_id) VALUES ('OP923QR', 15, 8, 2019, 45000, 'Arancione', 24000, false, null);
INSERT INTO Car (licenseplate, model_id, brand_id, yearofproduction, mileage, color, price, sold, owner_id) VALUES ('ST456UV', 16, 8, 2021, 32000, 'Argento', 27000, false, null);
INSERT INTO Car (licenseplate, model_id, brand_id, yearofproduction, mileage, color, price, sold, owner_id) VALUES ('WX789YZ', 17, 9, 2020, 28000, 'Bianco', 25000, false, null);
INSERT INTO Car (licenseplate, model_id, brand_id, yearofproduction, mileage, color, price, sold, owner_id) VALUES ('YZ123AB', 18, 9, 2022, 33000, 'Nero', 29000, false, null);
